Support and test for OTP 25
commanded/commanded pull request #489
Opened 2022-07-27 07:27 UTC by dvic

2022-07-27 07:29 UTC, dvic commented
I think there was a small "bug" that causes troubles on OTP 25 that is fixed in this PR, the failing test was:

```
1) test aggregate lifespan should adhere to aggregate lifespan after taking snapshot (Commanded.Aggregates.AggregateLifespanTest)
     test/aggregates/aggregate_lifespan_test.exs:247
     Assertion failed, no matching message after 1000ms
     The following variables were pinned:
       ref = #Reference<0.1955749089.1531969538.96562>
     Showing 1 of 1 message in the mailbox
     code: assert_receive {:DOWN, ^ref, :process, _pid, :normal}
     mailbox:
       pattern: {:DOWN, ^ref, :process, _pid, :normal}
       value:   {
                  :DOWN,
                  #Reference<0.1955749089.1531969538.96562>,
                  :process,
                  #PID<0.734.0>,
                  {:bad_return_value, {:noreply, %Commanded.Aggregates.Aggregate{aggregate_module: Commanded.Aggregates.LifespanAggregate, aggregate_state: %Commanded.Aggregates.LifespanAggregate{lifespan: :stop, reply_to: nil, uuid: "fec5e651-3abc-4ed2-ada0-23bb40e63be9"}, aggregate_uuid: "fec5e651-3abc-4ed2-ada0-23bb40e63be9", aggregate_version: 2, application: Commanded.DefaultApp, lifespan_timeout: {:stop, :normal}, snapshotting: %Commanded.Snapshotting{application: Commanded.DefaultApp, snapshot_every: 2, snapshot_module_version: 1, snapshot_version: 0, source_uuid: "fec5e651-3abc-4ed2-ada0-23bb40e63be9"}}, {:stop, :normal}}}
                }
     stacktrace:
       test/aggregates/aggregate_lifespan_test.exs:268: (test)
```

2022-08-07 16:52 UTC, slashdotdash requested changes

2022-08-07 16:52 UTC, slashdotdash commented on lib/commanded/aggregates/aggregate.ex
> +      {:noreply, state}
This bug should be fixed as follows:

```elixir
case lifespan_timeout do
  {:stop, reason} ->
    {:stop, reason, state}

  lifespan_timeout ->
    {:noreply, state, lifespan_timeout}
end
```

2022-08-07 16:54 UTC, slashdotdash commented on lib/commanded/aggregates/aggregate.ex
> +      {:noreply, state}
I will merge the pull request and apply the above fix.

2022-08-07 16:54 UTC, merged