Batching support
commanded/commanded pull request #569
Opened 2024-09-20 21:39 UTC by fmterrorf

This adds the option of having batched event handlers to speed things up. Please refer to the included documentation for details.

This PR is mostly taken from https://github.com/commanded/commanded/pull/509

2024-09-20 21:46 UTC, cdegroot commented
Note: review can wait until Calmwave has dogfooded this for a bit.

2024-12-03 01:15 UTC, drteeth requested changes
Really great work, I think it's very close. I think it needs 2 things:

1) The InMemory adapter needs to serve up batches of events
2) The branch needs a reqbase against master

2024-12-03 01:15 UTC, drteeth commented on lib/commanded/event_store/adapter.ex
> +       verified for EventStoreDB.
~~Looks like the InMemory implementation is done~~. I think we can go ahead without EventStoreDB as I don't think it's going to see much use going forward.

2024-12-03 01:15 UTC, drteeth commented on lib/commanded/event_store/adapter.ex
> +       verified for EventStoreDB.
I'd like to see the InMemory adapter implement batching as well before we merge.

2025-01-14 11:51 UTC, anderslemke commented
I'm rooting for this 🫶

2025-02-26 17:44 UTC, cblage commented on lib/commanded/event_store/adapter.ex
> +       verified for EventStoreDB.
Hi @drteeth,

From giving a second read at the code, it seems like the InMemory handler already implements the desired behavior of "acknowledging" the previous events in a batch here: https://github.com/calmwave-open-source/commanded/blob/batching-support/lib/commanded/event_store/adapters/in_memory/subscriber.ex#L17-L20

Given that, could you perhaps clarify what further work would be needed? The tests have been fixed and the branch updated with the latest upstream version.

Thanks!
Carlos

2025-06-03 23:02 UTC, drteeth requested changes
Looking good, just a little bit more to go.

2025-06-03 23:02 UTC, drteeth commented on lib/commanded/event/handler.ex
> +              failed_event :: domain_event | [domain_event] | nil,
At the very least the custom error module case needs to be dealt with:
https://github.com/commanded/commanded/blob/2e11e275641021a0144d6312e18de218f51053f3/lib/commanded/event/handler.ex#L1346

2025-06-05 13:42 UTC, cblage commented on test/event/event_handler_state_test.exs
> +      Process.exit(handler, :kill)
It was causing sometimes error logs in the tests, since it would continue processing events in the background and the Mock was only expecting 1 event.

2025-06-05 13:43 UTC, cblage commented on devbox.lock
> +{
I can remove it.

2025-06-06 21:07 UTC, cdegroot commented on lib/commanded/event/handler.ex
> +              failed_event :: domain_event | [domain_event] | nil,
Agree, we can do without the nil here.

2025-06-24 17:00 UTC, drteeth approved these changes

2025-06-25 13:58 UTC, merged

2025-08-26 14:05 UTC, badazz91 commented
hey @drteeth, @cdegroot  - is there some documentation / guidelines on how to use this new feature? I would be really eager to try this out in our production app - if suitable :)